# Generated by Django 3.0.2 on 2020-02-13 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptsDatas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('text', models.CharField(max_length=200)),
                ('start', models.DecimalField(decimal_places=3, max_digits=6)),
                ('duration', models.DecimalField(decimal_places=3, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='YoutubeDatas',
            fields=[
                ('youtube_id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('scripts', models.ManyToManyField(to='my_cake.ScriptsDatas')),
            ],
        ),
    ]
